# Generated by Django 6.0.1 on 2026-04-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='designation',
            field=models.CharField(default='Resident Medical Officer', help_text='e.g., Head of Department, Senior Consultant, etc.', max_length=100),
        ),
    ]
