# Generated by Django 6.0.1 on 2026-04-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_doctor_designation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('appointment', 'patient')},
        ),
    ]
