# Generated by Django 6.0.1 on 2026-04-15 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['experience_years', 'name']},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
        migrations.AddField(
            model_name='doctor',
            name='primary_specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_doctors', to='appointment.specialization', verbose_name='Primary Specialization'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='secondary_specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_doctors', to='appointment.specialization', verbose_name='Secondary Specialization'),
        ),
    ]
