# Generated by Django 6.0.1 on 2026-04-15 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_alter_doctor_options_remove_doctor_specialization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='primary_specialization',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='secondary_specialization',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.specialization'),
        ),
    ]
