# Generated by Django 6.0.1 on 2026-04-17 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_remove_doctor_primary_specialization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicines',
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Paracetamol 500mg', max_length=200)),
                ('dosage', models.CharField(blank=True, help_text='e.g. 1-0-1', max_length=100)),
                ('duration', models.CharField(blank=True, help_text='e.g. 5 Days', max_length=100)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines_list', to='appointment.prescription')),
            ],
        ),
    ]
