# Generated by Django 6.0.1 on 2026-04-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_remove_prescription_medicines_prescriptionmedicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.TextField(default='', help_text='Format: Medicine Name - Dosage - Duration'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PrescriptionMedicine',
        ),
    ]
