# Generated by Django 6.0.1 on 2026-04-24 08:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0016_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(help_text='e.g. Blood Test, MRI Scan', max_length=200)),
                ('pdf_file', models.FileField(help_text='Upload a PDF file only.', upload_to='medical_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='appointment.patient')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
