# Generated by Django 6.0.1 on 2026-04-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0017_add_medical_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='last_reminder_hour',
            field=models.IntegerField(default=-1, help_text='Tracks the last hour (0-23) a reminder email was sent. -1 means never sent.'),
        ),
    ]
