# Generated by Django 6.0.1 on 2026-04-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0018_add_last_reminder_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='advice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medications',
            field=models.JSONField(default=list, help_text='Format: [{"name": "...", "dose": "...", "timing": "...", "days": "..."}]'),
        ),
    ]
