# Generated by Django 6.0.1 on 2026-04-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0019_prescription_advice_prescription_diagnosis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicines',
        ),
    ]
