# Generated by Django 6.0.1 on 2026-04-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0020_remove_prescription_instructions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='advice',
            new_name='instructions',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medications',
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.TextField(default='', help_text='Format: Medicine Name - Dosage - Duration'),
            preserve_default=False,
        ),
    ]
