# Generated by Django 6.0.1 on 2026-05-01 15:34

from django.db import migrations
from django.contrib.auth.hashers import make_password
import os

def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='admin').exists():
        User.objects.create(
            username='admin',
            email='admin@example.com',
            password=make_password('admin123'),
            is_superuser=True,
            is_staff=True,
            is_active=True
        )

class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0021_rename_advice_prescription_instructions_and_more'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
